apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app:  apache
    spec:
      containers:
        - name:  apache
          image: webdevops/php-apache
          ports:
           - containerPort: 80
             name:  apache

---
apiVersion: v1
kind: Service
metadata:
  name:  phpservice
spec:
  selector:
    app: apache
  ports:
   - protocol: TCP
     port:  80
     targetPort: 80
     nodePort: 30080
  type:  LoadBalancer
